### PR TITLE
New gitignore

### PR DESCRIPTION
**Pull request by TheKnarf**
- Remove the `.DS_Store` file left in the repo
- Update to a proper `.gitignore` setup

Using templates from `gitignore.io`:

- Ignoring common operating system files from MacOS, Windows, Linux
- Ignoring common IDE's like Visual Studio Code and IntelliJ
- Ignoring files related to Node.js

### CODE REVIEW

**Comment by thecooltechguy** [comment]
Thanks for this PR! Will merge

**Comment by thecooltechguy** [comment]
@TheKnarf Would it be possible to remove `dist` from `.gitignore`?

As explained in https://github.com/ComfyWorkflows/ComfyUI-Launcher/pull/15#issuecomment-1986285218, currently this is used to make sure the end user doesn't need npm/node to be able to run the Launcher, since the web frontend is already built into html/css/js files for them.

**Comment by TheKnarf** [comment]
Updated PR to reflect your comment.

`dist` is no longer gitignored in this PR.

**Comment by dylanintech** [comment]
hey @TheKnarf  - we're going to review this PR as soon as possible, we've just been super busy with fixing docker installation on windows (https://github.com/ComfyWorkflows/ComfyUI-Launcher/issues/9, https://github.com/ComfyWorkflows/ComfyUI-Launcher/issues/8). thank you for your patience!

**Pull request closed without merging**
