### PR TITLE
places SELECT buttons to the left side

### PR DESCRIPTION
**Pull request by K2adir**
This Tailwind edit places the select button on the left side, allowing users to easily read and select the missing models. Previously, the UI placed the select button to the right, making it hard to recognize which select button belongs to the available module, especially on wide screens.

Before:
Screenshot 2024-03-07 at 7 01 41 PM

after 
Screenshot 2024-03-07 at 7 01 56 PM

Note: I didn't make any changes on the index.tsx, prettier changed it's formatting

### CODE REVIEW

**Comment by K2adir** [comment]
Not sure why Prettier changed the formatting this much. Perhaps, the project is missing prettier configs?

**Comment by thecooltechguy** [comment]
Thanks for this PR @K2adir ! Will review + merge this.

Also, we don't yet have any prettier configs setup haha, will look into it. 
If you have any recommended prettier configs, would love to know!

**Comment by thecooltechguy** [comment]
@K2adir I just added some prettier configs to the `web/` folder in the `main` branch, can you kindly push another commit that runs the prettier formatter in your version of the `web/` folder, which should resolve all conflicts?

thanks!

**Comment by K2adir** [comment]
> @K2adir I just added some prettier configs to the `web/` folder in the `main` branch, can you kindly push another commit that runs the prettier formatter in your version of the `web/` folder, which should resolve all conflicts?
> 
> thanks!

sure! on it

**Comment by dylanintech** [comment]
hey @K2adir - we're going to review this PR as soon as possible, we've just been super busy with fixing docker installation on windows (#9, #8). thank you for your contribution and patience!

**Comment by thecooltechguy** [comment]
Thanks for this PR @K2adir , just merged! :)

**Pull request merged**
